# Generated by Django 4.2.6 on 2023-12-26 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jozve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('jozve', models.FileField(upload_to='media/jozve')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('father_name', models.CharField(blank=True, max_length=128, null=True)),
                ('score_all', models.IntegerField(default=0)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='media/avatar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score_monthly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('farvardin', 'فروردین'), ('ordibehesht', 'اردیبهشت'), ('khordad', 'خرداد'), ('tir', 'تیر'), ('mordad', 'مرداد'), ('shahrivar', 'شهریور'), ('mehr', 'مهر'), ('aban', 'آبان'), ('azar', 'آذر'), ('dey', 'دی'), ('bahman', 'بهمن'), ('esfand', 'اسفند')], max_length=128)),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('farvardin', 'فروردین'), ('ordibehesht', 'اردیبهشت'), ('khordad', 'خرداد'), ('tir', 'تیر'), ('mordad', 'مرداد'), ('shahrivar', 'شهریور'), ('mehr', 'مهر'), ('aban', 'آبان'), ('azar', 'آذر'), ('dey', 'دی'), ('bahman', 'بهمن'), ('esfand', 'اسفند')], max_length=128)),
                ('say_pray', models.IntegerField(default=0)),
                ('setad_namaz', models.IntegerField(default=0)),
                ('payegah', models.IntegerField(default=0)),
                ('gharaat', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
